apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-node-drainer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-node-drainer
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - "*"
  resources:
  - pods
  - namespaces
  verbs:
  - list
- apiGroups:
  - "*"
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - "*"
  resources:
  - nodes
  verbs:
  - get
  - watch
  - list
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-node-drainer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-node-drainer
subjects:
- kind: ServiceAccount
  name: k8s-node-drainer
  namespace: kube-system
