name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: test the secret
      run: echo ${{ secrest.TEST1 }} | wc -l 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag logmein/k8s-node-drainer:$(date +%s)
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Publish the Docker Image
      run: docker push --tag logmein/k8s-node-drainer:$(date +%s)
    - name: Logot of the DockerHub Registry
      run: docker logout
