name: Docker Image CI

on: 
  push:
    branches:
    - master


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag logmein/k8s-node-drainer:latest
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
    - name: Publish the Docker Image
      run: docker push logmein/k8s-node-drainer:latest
    - name: Logot of the DockerHub Registry
      run: docker logout
